# Generated by Django 5.2.8 on 2025-11-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game_mode',
            field=models.CharField(choices=[('EASY', 'Easy'), ('HARD', 'Hard'), ('AI_MATCH', 'AI Match')], default='EASY', max_length=20),
        ),
    ]
